name: PartnerTools
main: org.golde.bukkit.auiypartnertools.Main
version: 1.7
author: Eric Golde
description: A custom partner tools plugin for JungleHCF
website: http://eric.golde.org/
commands:
   pitems:
      description: Stap your cheatin
      usage: /pitems <item>